<a href="https://colab.research.google.com/github/anderson-perez/Aulas-de-IEC/blob/main/KMeans_DBSCAN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aprendizado não-supervisionado

- Algoritmo KMEANS
- Algoritmo DBSCAN

In [1]:
from sklearn.datasets import make_blobs
from sklearn.datasets import make_moons

# KMeans
- Clusteriza os dados com base nas médias de distância.

In [2]:
from sklearn.cluster import KMeans

In [3]:
X_blobs, y_blobs = make_blobs(n_samples=100, centers=3)

In [5]:
y_blobs

array([0, 0, 0, 1, 0, 2, 0, 1, 2, 0, 1, 1, 2, 0, 2, 1, 1, 0, 1, 0, 1, 2,
       1, 2, 0, 1, 0, 0, 2, 1, 1, 1, 0, 0, 1, 0, 1, 1, 2, 0, 0, 1, 1, 0,
       1, 0, 0, 2, 1, 1, 2, 2, 1, 2, 1, 1, 2, 0, 2, 1, 2, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 2, 0, 0, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0,
       1, 0, 2, 1, 0, 2, 1, 0, 0, 2, 2, 2])

In [6]:
import plotly.express as ex

In [7]:
fig = ex.scatter(x=X_blobs[:,0], y=X_blobs[:,1])
fig.show()

In [8]:
kmeans_blobs =KMeans(n_clusters=3)

In [9]:
kmeans_blobs.fit(X_blobs)

KMeans(n_clusters=3)

In [10]:
labels_k_blobs = kmeans_blobs.labels_

In [13]:
centroides = kmeans_blobs.cluster_centers_

In [14]:
centroides

array([[ 9.32745844, -3.1638891 ],
       [ 6.7107465 ,  4.41978582],
       [ 4.91987669,  9.65585987]])

In [15]:
import plotly.graph_objects as go

In [16]:
fig1 = ex.scatter(x=X_blobs[:,0], y=X_blobs[:,1], color=labels_k_blobs)
fig2 = ex.scatter(x=centroides[:,0], y=centroides[:,1], size=[7,7,7])
fig3 = go.Figure(data=fig1.data + fig2.data)
fig3.show()

# Algoritmo DBSCAN - Density Based Spatial Clustering Application with Noisy

In [17]:
from sklearn.cluster import DBSCAN

In [32]:
dbscan_blobs = DBSCAN(eps=2)

In [33]:
dbscan_blobs.fit(X_blobs)

DBSCAN(eps=2)

In [34]:
labels_db_blobs = dbscan_blobs.labels_

In [21]:
labels_db_blobs

array([-1,  1, -1, -1, -1, -1, -1, -1, -1, -1,  0,  0,  3, -1, -1, -1,  0,
       -1,  2, -1,  0,  3, -1, -1,  4,  2, -1, -1, -1,  0,  2,  0,  1, -1,
        0, -1, -1, -1, -1,  4, -1,  2,  0, -1, -1, -1,  1, -1, -1,  0,  3,
       -1,  0,  3, -1,  0, -1, -1, -1,  0, -1,  1,  1, -1, -1, -1, -1, -1,
       -1,  1, -1, -1,  4, -1, -1,  4, -1, -1, -1, -1,  3, -1, -1, -1, -1,
       -1, -1,  1,  2,  1,  3,  0, -1, -1, -1,  4,  4, -1, -1, -1])

In [22]:
import numpy as np

In [35]:
np.unique_counts(labels_db_blobs)

UniqueCountsResult(values=array([0, 1]), counts=array([67, 33]))

In [36]:
fig11 = ex.scatter(x=X_blobs[:,0], y=X_blobs[:,1], color=labels_db_blobs)
#fig21 = ex.scatter(x=centroides[:,0], y=centroides[:,1], size=[7,7,7])
#fig31 = go.Figure(data=fig1.data + fig2.data)
fig11.show()

In [40]:
import pandas as pd

In [41]:
casas = pd.read_csv('/content/housing.csv')

In [42]:
casas.head(3)

longitude  latitude  ...  median_house_value  ocean_proximity
0    -122.23     37.88  ...            452600.0         NEAR BAY
1    -122.22     37.86  ...            358500.0         NEAR BAY
2    -122.24     37.85  ...            352100.0         NEAR BAY

[3 rows x 10 columns]

In [45]:
casas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [43]:
X = casas.iloc[:, 0:2].values

In [44]:
X

array([[-122.23,   37.88],
       [-122.22,   37.86],
       [-122.24,   37.85],
       ...,
       [-121.22,   39.43],
       [-121.32,   39.43],
       [-121.24,   39.37]])

In [46]:
fig_casas = ex.scatter(x = X[:,0], y = X[:,1])
fig_casas.show()

In [47]:
from sklearn.preprocessing import StandardScaler

In [48]:
standard = StandardScaler()

In [49]:
X_padronizado = standard.fit_transform(X)

In [50]:
X_padronizado

array([[-1.32783522,  1.05254828],
       [-1.32284391,  1.04318455],
       [-1.33282653,  1.03850269],
       ...,
       [-0.8237132 ,  1.77823747],
       [-0.87362627,  1.77823747],
       [-0.83369581,  1.75014627]])

In [51]:
kmeans_casas = KMeans(n_clusters=3, random_state=0)

In [52]:
kmeans_casas.fit(X_padronizado)

KMeans(n_clusters=3, random_state=0)

In [53]:
labels_kmeans_casas = kmeans_casas.labels_

In [54]:
centroides_casas = kmeans_casas.cluster_centers_

In [57]:
fig_casas = ex.scatter(x = X_padronizado[:,0], y =X_padronizado[:,1], color=labels_kmeans_casas)
fig_casas2 = ex.scatter(x = centroides_casas[:,0], y = centroides_casas[:,1], size=[6, 6, 6])
fig_casas3 = go.Figure(data = fig_casas.data + fig_casas2.data)
fig_casas3.show()

In [68]:
dbscan_casas = DBSCAN(eps=0.1)

In [69]:
dbscan_casas.fit(X_padronizado)

DBSCAN(eps=0.1)

In [70]:
fig_casas_db = ex.scatter(x = X_padronizado[:,0], y =X_padronizado[:,1], color=dbscan_casas.labels_)
#fig_casas2_db = ex.scatter(x = centroides_casas[:,0], y = centroides_casas[:,1], size=[6, 6, 6])
#fig_casas3_db = go.Figure(data = fig_casas_db.data + fig_casas2.data)
fig_casas_db.show()

In [ ]:
# Na próxima aula iremos dar continuidade aos estudos dos algoritmos KMEANS e DBSCAN.